module.exports = {
	'radio': [{
		"name": "jazz",
		"url": "https://jazzradio.ice.infomaniak.ch/jazzradio-high.mp3",
		"commande": "jazz"
	}, {
		"name": "nostalgie",
		"url": "https://scdn.nrjaudio.fm/fr/30601/mp3_128.mp3?origine=fluxradios&cdn_path=audio_lbs8",
		"commande": "nostalgie" 
	}, {
		"name": "rire&chanson",
		"url": "https://scdn.nrjaudio.fm/fr/30401/mp3_128.mp3?origine=fluxradios&cdn_path=audio_lbs7",
		"commande": "rire&chanson" 
	}, {
		"name": "rmc",
		"url": "https://chai5she.cdn.dvmr.fr:443/rmcinfo",
		"commande": "rmc" 
	}, {
		"name": "rtl",
		"url": "https://icecast.rtl.fr/rtl-1-44-128",
		"commande": "rtl" 
	}, {
		"name": "rtl2",
		"url": "https://icecast.rtl.fr/rtl2-1-44-128",
		"commande": "rtl2" 
	}, {
		"name": "nrj",
		"url": "https://scdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3?origine=fluxradios",
		"commande": "nrj" 
	}, {
		"name": "rfm",
		"url": "https://ais-live.cloud-services.paris:8443/rfm.mp3",
		"commande": "rfm" 
	}, {
		"name": "radionova",
		"url": "https://radionova.ice.infomaniak.ch/radionova-high.mp3",
		"commande": "radionova" 
	}, {
		"name": "franceinter",
		"url": "https://icecast.radiofrance.fr/franceinter-midfi.mp3",
		"commande": "franceinter" 
	}, {
		"name": "franceinfo",
		"url": "https://icecast.radiofrance.fr/franceinfo-midfi.mp3",
		"commande": "franceinfo" 
	}, {
		"name": "francebleu",
		"url": "https://icecast.radiofrance.fr/fb1071-midfi.mp3",
		"commande": "francebleu" 
	}, {
		"name": "franceculture",
		"url": "https://icecast.radiofrance.fr/franceculture-midfi.mp3",
		"commande": "franceculture" 
	}, {
		"name": "francemusique",
		"url": "https://icecast.radiofrance.fr/francemusique-midfi.mp3",
		"commande": "francemusique" 
	}, {
		"name": "radiofip",
		"url": "https://icecast.radiofrance.fr/fip-midfi.mp3",
		"commande": "radiofip" 
	}, {
		"name": "europe1",
		"url": "https://ais-live.cloud-services.paris:8443/europe1.mp3",
		"commande": "europe1" 
	}, {
		"name": "skyrock",
		"url": "https://icecast.skyrock.net/s/natio_mp3_128k?type=.mp3",
		"commande": "skyrock" 
	}, {
		"name": "virginradio",
		"url": "https://ais-live.cloud-services.paris:8443/virgin.mp3",
		"commande": "virginradio"
	}, {
		"name": "funradio",
		"url": "https://icecast.rtl.fr/fun-1-44-128",
		"commande": "funradio" 
	}, {
		"name": "bfmbusiness",
		"url": "https://chai5she.cdn.dvmr.fr/bfmbusiness",
		"commande": "bfmbusiness" 
	}, {
		"name": "lemouv",
		"url": "https://icecast.radiofrance.fr/mouv-midfi.mp3",
		"commande": "lemouv" 
	}, {
		"name": "cheriefm",
		"url": "https://scdn.nrjaudio.fm/audio1/fr/30201/mp3_128.mp3?origine=fluxradios",
		"commande": "cheriefm" 
	}, {
		"name": "mfmradio",
		"url": "https://mfm.ice.infomaniak.ch/mfm-128.mp3",
		"commande": "mfmradio" 
	}, {
		"name": "radiolatina",
		"url": "http://start-latina.ice.infomaniak.ch/start-latina-high.mp3",
		"commande": "radiolatina" 
	}, {
		"name": "ouifm",
		"url": "http://stream.ouifm.fr/ouifm-high.mp3",
		"commande": "ouifm" 
	}, {
		"name": "radioswissjazz",
		"url": "http://stream.srg-ssr.ch/m/rsj/mp3_128",
		"commande": "radioswissjazz" 
	}, {
		"name": "tsfjazz",
		"url": "https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3",
		"commande": "tsfjazz" 
	}, {
		"name": "radioclassic&jazz",
		"url": "http://broadcast.infomaniak.net/jazz-wr01-128.mp3",
		"commande": "radioclassic&jazz" 
	}, {
		"name": "radioclassique",
		"url": "https://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3",
		"commande": "radioclassique" 
	}, {
		"name": "nrj",
		"url": "https://scdn.nrjaudio.fm/fr/30601/mp3_128.mp3?origine=fluxradios&cdn_path=audio_lbs8",
		"commande": "nrj"
	}, {
		"name": "generations",
		"url": "https://generationfm.ice.infomaniak.ch/generationfm-high.mp3",
		"commande": "generations" 
	}, {
		"name": "vibration",
		"url": "https://vibration.ice.infomaniak.ch/vibration-high.mp3",
		"commande": "vibration" 
	}, {
		"name": "voltage",
		"url": "https://start-voltage.ice.infomaniak.ch/start-voltage-high.mp3",
		"commande": "voltage" 
	}, {
		"name": "contact",
		"url": "https://radio-contact.ice.infomaniak.ch/radio-contact-high.mp3",
		"commande": "contact" 
	}, {
		"name": "radiofg",
		"url": "https://radiofg.impek.com/fg",
		"commande": "radiofg" 
	}, {
		"name": "classique21",
		"url": "https://radios.rtbf.be/classic21-128.mp3",
		"commande": "classique21" 
	}, {
		"name": "rfimonde",
		"url": "http://live02.rfi.fr/rfimonde-64.mp3",
		"commande": "rfimonde" 
	}, {
		"name": "hotmixradio",
		"url": "http://streamingads.hotmixradio.fm/hotmixradio-dance-128.mp3",
		"commande": "hotmixradio" 
	}, {
		"name": "radioscoop",
		"url": "https://radioscooplyon.ice.infomaniak.ch/radioscoop-lyon-128.mp3",
		"commande": "radioscoop" 
	}, {
		"name": "ado",
		"url": "https://start-adofm.ice.infomaniak.ch/start-adofm-high.mp3",
		"commande": "ado" 
	}, {
		"name": "radiomeuh",
		"url": "https://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3",
		"commande": "radiomeuh" 
	}, {
		"name": "sudradio",
		"url": "http://broadcast.infomaniak.net/start-sud-high.mp3",
		"commande": "sudradio" 
	}, {
		"name": "witfm",
		"url": "https://start-witfm.ice.infomaniak.ch/start-witfm-high.mp3",
		"commande": "witfm" 
	}
]
}